steps:
- name: 'gcr.io/cloud-builders/docker'
  id: Pull docker cache
  entrypoint: 'bash'
  args:
  - '-c'
  - |
   docker pull gcr.io/$PROJECT_ID/ci-example:latest || exit 0
- name: gcr.io/cloud-builders/docker
  id: Build Image
  args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/ci-example',
      '--cache-from', 'gcr.io/$PROJECT_ID/ci-example:latest',
      './'
    ]