steps:
- name: 'gcr.io/cloud-builders/docker'
  id: Pull docker cache
  entrypoint: 'bash'
  args:
  - '-c'
  - |
   docker pull gcr.io/$PROJECT_ID/airflow-dags-builder:latest || exit 0
- name: gcr.io/cloud-builders/docker
  id: Build Airflow DAGs Builder
  args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/airflow-dags-builder',
      '--cache-from', 'gcr.io/$PROJECT_ID/airflow-dags-builder:latest',
      './'
    ]
  dir: ${_DIRECTORY}
- name: 'gcr.io/$PROJECT_ID/airflow-dags-builder'
  id: Validation Test
  entrypoint: python
  env:
  - AIRFLOW__CORE__DAGS_FOLDER=/workspace/${_DIRECTORY}/dags
  args:
  - -m
  - unittest
  - tests/dag_integrity_test.py
  dir: ${_DIRECTORY}
- name: 'gcr.io/$PROJECT_ID/airflow-dags-builder'
  id: End to End Test
  entrypoint: bash
  env:
  - AIRFLOW__CORE__DAGS_FOLDER=/workspace/${_DIRECTORY}/dags
  dir: ${_DIRECTORY}
  args:
  - -c
  - |
    pwd
    ls -l
    airflow initdb
    airflow variables -s input gs://test-input-bucket/
    airflow variables -s output gs://test-output-bucket/
    airflow backfill echo_and_wait --start_date=2020-01-03 --end_date=2020-01-03
    ret=$?
    find /workspace/airflow/logs/ -type f -name *.log | sort | xargs cat
    # Fail if the backfill failed.
    exit $ret
- name: gcr.io/cloud-builders/gsutil
  id: Deploy DAGs
  args:
  - -m
  - rsync
  - -r
  - -c
  - -x
  - .*\.pyc|airflow_monitoring.py
  - /workspace/${_DIRECTORY}/dags/
  - ${_DEPLOY_DAGS_LOCATION}
  dir: ${_DIRECTORY}
images: ['gcr.io/$PROJECT_ID/airflow-dags-builder:latest']