steps:
- name: 'gcr.io/cloud-builders/docker'
  id: Pull docker cache
  entrypoint: 'bash'
  args:
  - '-c'
  - |
   docker pull gcr.io/$PROJECT_ID/airflow-data-pipeline:latest || exit 0
- name: gcr.io/cloud-builders/docker
  id: Build Airflow DAGs Builder
  args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/airflow-data-pipeline',
      '--cache-from', 'gcr.io/$PROJECT_ID/airflow-data-pipeline:latest',
      './'
    ]
- name: 'gcr.io/$PROJECT_ID/airflow-data-pipeline'
  id: Validation Test
  entrypoint: python
  env:
  - AIRFLOW__CORE__DAGS_FOLDER=/workspace/dags
  args:
  - -m
  - unittest
  - tests/dag_tests.py
- name: gcr.io/cloud-builders/docker
  id: Push Image to GCR
  args: [
      'push',
      'gcr.io/$PROJECT_ID/airflow-data-pipeline:latest'
    ]
- name: gcr.io/cloud-builders/gsutil
  id: Deploy DAGs
  args:
  - -m
  - rsync
  - -r
  - -c
  - -x
  - .*\.pyc|airflow_monitoring.py
  - /workspace/dags
  - ${_DEPLOY_DAGS_LOCATION}
images: ['gcr.io/$PROJECT_ID/airflow-data-pipeline:latest']